import GlobalContextProvider from "@/Components/GlobalContextProvider";
import { ThemeProvider } from "@/Components/ThemeProvider";
import { ToastContainer } from "react-toastify";
import NextJsTOpLoader from "nextjs-toploader";
import { Inter } from "next/font/google";
import Navbar from "@/Components/Navbar";
import type { Metadata } from "next";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GlobalContextProvider>
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            disableTransitionOnChange
          >
            <Navbar />
            <ToastContainer />
            <NextJsTOpLoader color="#15e5e8" />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </GlobalContextProvider>
  )
};